In [1]:
# August 23 2018: Another fresh attempt on model training

# connect to the PostgreSQL instance
import psycopg2 as pg

# custom python library created to store the db configuation details
from config import config

# load the object with the default database parameters required
params = config()

# connect to the PostgreSQL server
conn = pg.connect(**params)

curs = conn.cursor()

# manually update the iteration count
iCnt = 0 # 0,1

# threshold
thrhld = 1000000

# execute SQL queries to the tables within the database
curs.execute('select * from DTML_MSTR_RAW where id between {0} and {1};'.format((iCnt*thrhld + 1), (iCnt*thrhld + thrhld)))

# query_op = curs.fetchone() # fetches only one record
query_op = curs.fetchall()

In [2]:
# print top 10 rows
for i in range(10):
    print(query_op[i])

(1, datetime.date(2017, 11, 6), 'AD98', 'A22-72740-000', '013', 'N', 'S', '009', '1', '2', 1, 44, 'N', Decimal('-0.99955476'), Decimal('0.99599287'), '(null)', 5, 0, 0, 0, 0, 0, 0, 0, 0, 4, Decimal('0.3330'), 0, 2, 196, 1, Decimal('-75.0000'), Decimal('10.8333'), 0, 0)
(2, datetime.date(2018, 4, 24), 'AD98', 'A22-69882-000', '034', 'N', 'S', '009', '1', '2', 0, 48, 'N', Decimal('-0.04341051'), Decimal('0.91495993'), '(null)', 0, 0, 0, 0, 3, 218, 0, 0, 798, 5, Decimal('0.0000'), 0, 7, 107, 9, Decimal('800.0000'), Decimal('4.3333'), 0, 0)
(3, datetime.date(2018, 5, 7), 'DN 4', 'DN EPG150230', '065', 'N', 'S', '009', '1', '2', 1, 12, 'N', Decimal('0.95547640'), Decimal('0.95547640'), '1', 0, 0, 0, 0, 0, 0, 0, 0, 19, 2, Decimal('0.0000'), 0, 13, 178, 3, Decimal('50.0000'), Decimal('2.0000'), 0, 0)
(4, datetime.date(2017, 10, 18), 'Z582', '04-31885-200', '065', 'N', 'S', '009', '1', '2', 1, 20, 'N', Decimal('-0.93455031'), Decimal('1.00000000'), '(null)', 0, 0, 0, 0, 0, 0, 0, 0, 20, 2, Decimal('0.0000'), 0, 12, 166, 5, Decimal('0.0000'), Decimal('2.5000'), 0, 0)
(5, datetime.date(2017, 12, 6), 'T606', '12-20828-000', '034', 'Y', 'S', '009', '1', '2', 5, 50, 'N', Decimal('-0.98441674'), Decimal('1.00000000'), '0.666', 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, Decimal('0.0000'), 0, 2, 108, 77, Decimal('6.9400'), Decimal('73.0000'), 15996, 118)
(6, datetime.date(2018, 2, 19), 'JK65', 'A05-19332-000', '065', 'N', 'S', '009', '1', '2', 1, 10, 'N', Decimal('-0.89047195'), Decimal('1.00000000'), '1', 2, 0, 0, 0, 0, 0, 0, 0, 12, 2, Decimal('0.0000'), 0, 12, 160, 17, Decimal('-58.5300'), Decimal('47.8333'), 0, 261)
(7, datetime.date(2018, 4, 16), 'ASC3', 'A18-64616-318', '001', 'N', 'S', '009', '1', '2', 1, 8, 'N', Decimal('0.00578807'), Decimal('0.97217275'), '(null)', 0, 0, 0, 0, 0, 0, 0, 0, 39, 10, Decimal('0.0000'), 1, 11, 27, 56, Decimal('-27.2700'), Decimal('58.1666'), 2919, 547)
(8, datetime.date(2017, 6, 21), 'ASC3', 'A18-69613-203', '001', 'N', 'S', '009', '1', '2', 1, 2, 'N', Decimal('-0.01024043'), Decimal('0.88668744'), '(null)', 0, 0, 0, 0, 0, 0, 0, 0, 8, 11, Decimal('0.2500'), 1, 11, 1, 45, Decimal('36.3600'), Decimal('54.6666'), 7481, 274)
(9, datetime.date(2017, 11, 13), 'B682', 'A12-28714-000', '034', 'N', 'S', '009', '1', '2', 1, 32, 'N', Decimal('-0.00512021'), Decimal('0.97128228'), '0.5', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, Decimal('0.0000'), 0, 7, 110, 4, Decimal('100.0000'), Decimal('3.3333'), 335, 0)
(10, datetime.date(2017, 5, 24), 'PYI', 'A22-69379-002', '001', 'N', 'S', '009', '4', '2', 1, 0, 'N', Decimal('0.95547640'), Decimal('0.95547640'), '(null)', 0, 0, 0, 0, 0, 0, 0, 0, 6, 1, Decimal('0.0000'), 0, 15, 24, 0, Decimal('0.0000'), Decimal('0.0000'), 0, 0)

In [3]:
import pandas as pd

df = pd.DataFrame(query_op)

print(type(df))
print(df.shape)
print(df.head())

<class 'pandas.core.frame.DataFrame'>
(1000000, 35)
   0           1     2              3    4  5  6    7  8  9  ...   25      26  \
0   1  2017-11-06  AD98  A22-72740-000  013  N  S  009  1  2 ...    4  0.3330
1   2  2018-04-24  AD98  A22-69882-000  034  N  S  009  1  2 ...    5  0.0000
2   3  2018-05-07  DN 4   DN EPG150230  065  N  S  009  1  2 ...    2  0.0000
3   4  2017-10-18  Z582   04-31885-200  065  N  S  009  1  2 ...    2  0.0000
4   5  2017-12-06  T606   12-20828-000  034  Y  S  009  1  2 ...    3  0.0000

  27  28   29  30        31       32     33   34
0  0   2  196   1  -75.0000  10.8333      0    0
1  0   7  107   9  800.0000   4.3333      0    0
2  0  13  178   3   50.0000   2.0000      0    0
3  0  12  166   5    0.0000   2.5000      0    0
4  0   2  108  77    6.9400  73.0000  15996  118

[5 rows x 35 columns]

In [4]:
# creating an explicit/distinct copy of the features
X_lowVar = df.copy()

In [5]:
# feature transformation

from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(threshold=(0.8 * (1 - 0.8)))

In [6]:
print(sel)

VarianceThreshold(threshold=0.15999999999999998)

In [8]:
# unless all the features are numercic, none of the scaling would work

In [9]:
# converting the features to numeric columns, one at a time

In [11]:
# adding the correct column names to the dataset
curs.execute("SELECT column_name FROM information_schema.columns WHERE table_name like 'dtml_mstr_raw';")

query_op = curs.fetchall()

df_header = list()
for i in range(len(query_op)):
    df_header.append(query_op[i][0])

In [13]:
print(df_header)

['id', 'cal_date', 'vndr_id', 'item_no', 'loc', 'sr_flag', 'crfa_c', 'crfa_r', 'crfa_f', 'crfa_a', 'eoq', 'pkg_qty', 'outproc_flag', 'score_edi_instability_avg', 'order_edi_instability_positive_only_avg', 'fulfillment_rate_2wkavg', 'spec_cng_elem', 'spec_cng_fpe', 'spec_cng_mrp', 'spec_cng_oh_adj', 'spec_cng_pcts', 'spec_cng_peg', 'spec_cng_por_asn', 'spec_cng_potr', 'spec_cng_sched', 'spec_cng_unknwn', 'dropin', 'past_dues', 'cur_intrn_days', 'mdl_bld_rate', 'prev_mnth_record_count', 'prev_mnth_percent', 'avg_six_mnth_cnt', 'shrt_ppm', 'qa_ppm']

In [14]:
# replace the indexes of the dataframe with the correct header columns by renaming them
for i in range(len(df.columns)):
    df.rename(columns={i:df_header[i]}, inplace=True)

In [15]:
## ------------------ ##
# cal_date
## ------------------ ##

# create a copy of the original feature dataset (df)
X_copy = df.copy()

# split the cal_date to multiple numeric columns

# convert the datatype to date first
X_copy['cal_date'] = pd.to_datetime(X_copy['cal_date'])

In [17]:
# split the data column into individual numeric info columns and append it back

X_split = pd.DataFrame({
    'year': X_copy['cal_date'].dt.year,
    'month': X_copy['cal_date'].dt.month,
    'day': X_copy['cal_date'].dt.day,
    'day_of_year': X_copy['cal_date'].dt.dayofyear,
    'week': X_copy['cal_date'].dt.week,
    'week_of_year': X_copy['cal_date'].dt.weekofyear,
    'day_of_week': X_copy['cal_date'].dt.dayofweek,
    'weekday': X_copy['cal_date'].dt.weekday,
    'quarter': X_copy['cal_date'].dt.quarter
}).join(X_copy)

In [21]:
X_split.head()

,year,month,day,day_of_year,week,week_of_year,day_of_week,weekday,quarter,id,...,spec_cng_unknwn,dropin,past_dues,cur_intrn_days,mdl_bld_rate,prev_mnth_record_count,prev_mnth_percent,avg_six_mnth_cnt,shrt_ppm,qa_ppm
0,2017,11,6,310,45,45,0,0,4,1,...,4,0.3330,0,2,196,1,-75.0000,10.8333,0,0
1,2018,4,24,114,17,17,1,1,2,2,...,5,0.0000,0,7,107,9,800.0000,4.3333,0,0
2,2018,5,7,127,19,19,0,0,2,3,...,2,0.0000,0,13,178,3,50.0000,2.0000,0,0
3,2017,10,18,291,42,42,2,2,4,4,...,2,0.0000,0,12,166,5,0.0000,2.5000,0,0
4,2017,12,6,340,49,49,2,2,4,5,...,3,0.0000,0,2,108,77,6.9400,73.0000,15996,118

In [22]:
# drop the original cal_date column from the X_split df
# X_split.drop('cal_date', axis='columns')

,year,month,day,day_of_year,week,week_of_year,day_of_week,weekday,quarter,id,...,spec_cng_unknwn,dropin,past_dues,cur_intrn_days,mdl_bld_rate,prev_mnth_record_count,prev_mnth_percent,avg_six_mnth_cnt,shrt_ppm,qa_ppm
0,2017,11,6,310,45,45,0,0,4,1,...,4,0.3330,0,2,196,1,-75.0000,10.8333,0,0
1,2018,4,24,114,17,17,1,1,2,2,...,5,0.0000,0,7,107,9,800.0000,4.3333,0,0
2,2018,5,7,127,19,19,0,0,2,3,...,2,0.0000,0,13,178,3,50.0000,2.0000,0,0
3,2017,10,18,291,42,42,2,2,4,4,...,2,0.0000,0,12,166,5,0.0000,2.5000,0,0
4,2017,12,6,340,49,49,2,2,4,5,...,3,0.0000,0,2,108,77,6.9400,73.0000,15996,118
5,2018,2,19,50,8,8,0,0,1,6,...,2,0.0000,0,12,160,17,-58.5300,47.8333,0,261
6,2018,4,16,106,16,16,0,0,2,7,...,10,0.0000,1,11,27,56,-27.2700,58.1666,2919,547
7,2017,6,21,172,25,25,2,2,2,8,...,11,0.2500,1,11,1,45,36.3600,54.6666,7481,274
8,2017,11,13,317,46,46,0,0,4,9,...,0,0.0000,0,7,110,4,100.0000,3.3333,335,0
9,2017,5,24,144,21,21,2,2,2,10,...,1,0.0000,0,15,24,0,0.0000,0.0000,0,0
10,2017,10,17,290,42,42,1,1,4,11,...,18,0.0000,0,6,81,53,82.7500,47.5000,1408,654
11,2018,3,23,82,12,12,4,4,1,12,...,3,0.3330,0,5,81,27,0.0000,30.8333,17404,4109
12,2018,5,2,122,18,18,2,2,2,13,...,5,0.0000,0,11,30,20,81.8100,13.3333,371,124
13,2017,7,25,206,30,30,1,1,3,14,...,0,0.0000,0,6,209,9,-78.0400,13.5000,983,0
14,2018,3,22,81,12,12,3,3,1,15,...,5,0.0000,0,7,81,31,-54.4100,41.6666,0,0
15,2017,12,1,335,48,48,4,4,4,16,...,34,0.5000,0,1,114,19,90.0000,15.6666,510,0
16,2017,8,2,214,31,31,2,2,3,17,...,3,0.0000,0,2,114,11,-31.2500,11.5000,678,0
17,2018,1,19,19,3,3,4,4,1,18,...,0,0.0000,0,6,114,7,-30.0000,10.1666,0,0
18,2018,5,7,127,19,19,0,0,2,19,...,6,0.0000,1,0,178,9,350.0000,3.6666,0,85
19,2018,1,11,11,2,2,3,3,1,20,...,0,0.0000,0,8,105,9,-40.0000,21.6666,106,0
20,2017,11,6,310,45,45,0,0,4,21,...,20,0.0000,0,7,196,1,-50.0000,0.8333,0,0
21,2017,10,17,290,42,42,1,1,4,22,...,22,0.2850,0,5,1,8,100.0000,3.1666,308,0
22,2017,8,31,243,35,35,3,3,3,23,...,16,0.0000,0,12,4,3,-25.0000,1.5000,0,0
23,2017,8,4,216,31,31,4,4,3,24,...,10,0.0000,0,14,101,7,-12.5000,5.5000,0,0
24,2018,2,22,53,8,8,3,3,1,25,...,1,0.0000,0,2,114,30,7.1400,21.3333,7591,0
25,2017,11,9,313,45,45,3,3,4,26,...,0,0.0000,0,1,154,9,125.0000,4.3333,0,145
26,2017,8,1,213,31,31,1,1,3,27,...,2,0.0000,0,7,214,74,-27.4500,58.1666,61,0
27,2017,6,9,160,23,23,4,4,2,28,...,4,0.0000,1,5,185,1,-83.3300,4.8333,0,0
28,2017,12,12,346,50,50,1,1,4,29,...,9,0.0000,0,7,78,16,-48.3800,18.1666,564,564
29,2017,11,16,320,46,46,3,3,4,30,...,2,0.0000,0,10,167,6,20.0000,9.8333,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,2017,12,13,347,50,50,2,2,4,999971,...,4,0.0000,0,4,78,12,-53.8400,29.8333,0,354
999971,2018,3,2,61,9,9,4,4,1,999972,...,2,0.1660,0,1,114,109,-14.1700,144.3333,4076,68
999972,2017,7,30,211,30,30,6,6,3,999973,...,33,0.0000,0,1,0,3,0.0000,2.0000,2577,3866
999973,2017,12,5,339,49,49,1,1,4,999974,...,3,0.0000,0,1,167,4,100.0000,2.3333,0,0
999974,2017,5,13,133,19,19,5,5,2,999975,...,15,0.0000,0,1,0,76,4.1000,74.6666,3511,195
999975,2017,8,5,217,31,31,5,5,3,999976,...,10,0.1420,0,8,101,54,-43.7500,63.5000,5186,1114
999976,2017,10,18,291,42,42,2,2,4,999977,...,4,0.0000,0,1,114,37,23.3300,29.8333,847,624
999977,2017,8,5,217,31,31,5,5,3,999978,...,19,0.0000,0,8,0,0,0.0000,0.0000,0,2764
999978,2017,10,31,304,44,44,1,1,4,999979,...,4,0.3750,0,4,114,32,28.0000,35.6666,1579,1612
999979,2017,7,31,212,31,31,0,0,3,999980,...,1,0.0000,0,1,114,20,300.0000,6.6666,0,0
999980,2018,1,29,29,5,5,0,0,1,999981,...,0,0.0000,0,7,114,16,23.0700,16.3333,0,0
999981,2018,1,10,10,2,2,2,2,1,999982,...,2,0.0000,0,10,25,20,-39.3900,48.3333,18314,95
999982,2018,2,1,32,5,5,3,3,1,999983,...,10,0.0000,0,9,1,3,-40.0000,5.5000,988,0
999983,2017,5,26,146,21,21,4,4,2,999984,...,10,0.1420,0,8,24,24,-4.0000,21.5000,986,0
999984,2018,5,20,140,20,20,6,6,2,999985,...,1,0.0000,0,12,0,249,329.3100,95.8333,15580,1343
999985,2017,5,24,144,21,21,2,2,2,999986,...,6,0.0000,0,8,200,0,0.0000,0.0000,0,0
999986,2017,6,18,169,24,24,6,6,2,999987,...,18,0.0000,0,2,0,5,-50.0000,7.8333,0,2519
999987,2018,3,11,70,10,10,6,6,1,999988,...,12,0.0000,0,9,0,2,0.0000,1.0000,0,0
999988,2017,12,29,363,52,52,4,4,4,999989,...,7,0.0000,0,8,0,12,300.0000,5.3333,4619,0
999989,2018,2,14,45,7,7,2,2,1,999990,...,3,0.0000,0,15,160,11,-35.2900,19.0000,0,0
999990,2018,2,10,41,6,6,5,5,1,999991,...,1,0.0000,0,6,1,1,0.0000,2.5000,0,0
999991,2017,11,20,324,47,47,0,0,4,999992,...,0,0.0000,0,6,114,122,12.9600,76.1666,7551,444
999992,2018,5,5,125,18,18,5,5,2,999993,...,3,0.0000,0,4,126,47,291.6600,27.3333,0,21
999993,2017,5,17,137,20,20,2,2,2,999994,...,0,0.0000,0,7,4,3,50.0000,2.0000,0,0
999994,2018,1,8,8,2,2,0,0,1,999995,...,3,0.0000,0,7,161,31,-24.3900,40.0000,0,0
999995,2017,11,22,326,47,47,2,2,4,999996,...,2,0.0000,0,7,108,10,-9.0900,11.8333,267,0
999996,2017,11,7,311,45,45,1,1,4,999997,...,8,0.3330,0,9,208,9,-66.6600,32.8333,286,0
999997,2018,4,3,93,14,14,1,1,2,999998,...,1,0.0000,0,5,210,4,300.0000,5.1666,0,11
999998,2018,2,28,59,9,9,2,2,1,999999,...,3,0.0000,0,6,211,51,-89.6700,155.8333,230,0
999999,2017,12,25,359,52,52,0,0,4,1000000,...,15,1.0000,0,5,0,1,-75.0000,3.1666,0,0

In [23]:
# reassign X_split to X_copy
X_copy = X_split

In [24]:
X_copy.head()

,year,month,day,day_of_year,week,week_of_year,day_of_week,weekday,quarter,id,...,spec_cng_unknwn,dropin,past_dues,cur_intrn_days,mdl_bld_rate,prev_mnth_record_count,prev_mnth_percent,avg_six_mnth_cnt,shrt_ppm,qa_ppm
0,2017,11,6,310,45,45,0,0,4,1,...,4,0.3330,0,2,196,1,-75.0000,10.8333,0,0
1,2018,4,24,114,17,17,1,1,2,2,...,5,0.0000,0,7,107,9,800.0000,4.3333,0,0
2,2018,5,7,127,19,19,0,0,2,3,...,2,0.0000,0,13,178,3,50.0000,2.0000,0,0
3,2017,10,18,291,42,42,2,2,4,4,...,2,0.0000,0,12,166,5,0.0000,2.5000,0,0
4,2017,12,6,340,49,49,2,2,4,5,...,3,0.0000,0,2,108,77,6.9400,73.0000,15996,118

In [25]:
X_copy.drop('cal_date', axis='columns')

,year,month,day,day_of_year,week,week_of_year,day_of_week,weekday,quarter,id,...,spec_cng_unknwn,dropin,past_dues,cur_intrn_days,mdl_bld_rate,prev_mnth_record_count,prev_mnth_percent,avg_six_mnth_cnt,shrt_ppm,qa_ppm
0,2017,11,6,310,45,45,0,0,4,1,...,4,0.3330,0,2,196,1,-75.0000,10.8333,0,0
1,2018,4,24,114,17,17,1,1,2,2,...,5,0.0000,0,7,107,9,800.0000,4.3333,0,0
2,2018,5,7,127,19,19,0,0,2,3,...,2,0.0000,0,13,178,3,50.0000,2.0000,0,0
3,2017,10,18,291,42,42,2,2,4,4,...,2,0.0000,0,12,166,5,0.0000,2.5000,0,0
4,2017,12,6,340,49,49,2,2,4,5,...,3,0.0000,0,2,108,77,6.9400,73.0000,15996,118
5,2018,2,19,50,8,8,0,0,1,6,...,2,0.0000,0,12,160,17,-58.5300,47.8333,0,261
6,2018,4,16,106,16,16,0,0,2,7,...,10,0.0000,1,11,27,56,-27.2700,58.1666,2919,547
7,2017,6,21,172,25,25,2,2,2,8,...,11,0.2500,1,11,1,45,36.3600,54.6666,7481,274
8,2017,11,13,317,46,46,0,0,4,9,...,0,0.0000,0,7,110,4,100.0000,3.3333,335,0
9,2017,5,24,144,21,21,2,2,2,10,...,1,0.0000,0,15,24,0,0.0000,0.0000,0,0
10,2017,10,17,290,42,42,1,1,4,11,...,18,0.0000,0,6,81,53,82.7500,47.5000,1408,654
11,2018,3,23,82,12,12,4,4,1,12,...,3,0.3330,0,5,81,27,0.0000,30.8333,17404,4109
12,2018,5,2,122,18,18,2,2,2,13,...,5,0.0000,0,11,30,20,81.8100,13.3333,371,124
13,2017,7,25,206,30,30,1,1,3,14,...,0,0.0000,0,6,209,9,-78.0400,13.5000,983,0
14,2018,3,22,81,12,12,3,3,1,15,...,5,0.0000,0,7,81,31,-54.4100,41.6666,0,0
15,2017,12,1,335,48,48,4,4,4,16,...,34,0.5000,0,1,114,19,90.0000,15.6666,510,0
16,2017,8,2,214,31,31,2,2,3,17,...,3,0.0000,0,2,114,11,-31.2500,11.5000,678,0
17,2018,1,19,19,3,3,4,4,1,18,...,0,0.0000,0,6,114,7,-30.0000,10.1666,0,0
18,2018,5,7,127,19,19,0,0,2,19,...,6,0.0000,1,0,178,9,350.0000,3.6666,0,85
19,2018,1,11,11,2,2,3,3,1,20,...,0,0.0000,0,8,105,9,-40.0000,21.6666,106,0
20,2017,11,6,310,45,45,0,0,4,21,...,20,0.0000,0,7,196,1,-50.0000,0.8333,0,0
21,2017,10,17,290,42,42,1,1,4,22,...,22,0.2850,0,5,1,8,100.0000,3.1666,308,0
22,2017,8,31,243,35,35,3,3,3,23,...,16,0.0000,0,12,4,3,-25.0000,1.5000,0,0
23,2017,8,4,216,31,31,4,4,3,24,...,10,0.0000,0,14,101,7,-12.5000,5.5000,0,0
24,2018,2,22,53,8,8,3,3,1,25,...,1,0.0000,0,2,114,30,7.1400,21.3333,7591,0
25,2017,11,9,313,45,45,3,3,4,26,...,0,0.0000,0,1,154,9,125.0000,4.3333,0,145
26,2017,8,1,213,31,31,1,1,3,27,...,2,0.0000,0,7,214,74,-27.4500,58.1666,61,0
27,2017,6,9,160,23,23,4,4,2,28,...,4,0.0000,1,5,185,1,-83.3300,4.8333,0,0
28,2017,12,12,346,50,50,1,1,4,29,...,9,0.0000,0,7,78,16,-48.3800,18.1666,564,564
29,2017,11,16,320,46,46,3,3,4,30,...,2,0.0000,0,10,167,6,20.0000,9.8333,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,2017,12,13,347,50,50,2,2,4,999971,...,4,0.0000,0,4,78,12,-53.8400,29.8333,0,354
999971,2018,3,2,61,9,9,4,4,1,999972,...,2,0.1660,0,1,114,109,-14.1700,144.3333,4076,68
999972,2017,7,30,211,30,30,6,6,3,999973,...,33,0.0000,0,1,0,3,0.0000,2.0000,2577,3866
999973,2017,12,5,339,49,49,1,1,4,999974,...,3,0.0000,0,1,167,4,100.0000,2.3333,0,0
999974,2017,5,13,133,19,19,5,5,2,999975,...,15,0.0000,0,1,0,76,4.1000,74.6666,3511,195
999975,2017,8,5,217,31,31,5,5,3,999976,...,10,0.1420,0,8,101,54,-43.7500,63.5000,5186,1114
999976,2017,10,18,291,42,42,2,2,4,999977,...,4,0.0000,0,1,114,37,23.3300,29.8333,847,624
999977,2017,8,5,217,31,31,5,5,3,999978,...,19,0.0000,0,8,0,0,0.0000,0.0000,0,2764
999978,2017,10,31,304,44,44,1,1,4,999979,...,4,0.3750,0,4,114,32,28.0000,35.6666,1579,1612
999979,2017,7,31,212,31,31,0,0,3,999980,...,1,0.0000,0,1,114,20,300.0000,6.6666,0,0
999980,2018,1,29,29,5,5,0,0,1,999981,...,0,0.0000,0,7,114,16,23.0700,16.3333,0,0
999981,2018,1,10,10,2,2,2,2,1,999982,...,2,0.0000,0,10,25,20,-39.3900,48.3333,18314,95
999982,2018,2,1,32,5,5,3,3,1,999983,...,10,0.0000,0,9,1,3,-40.0000,5.5000,988,0
999983,2017,5,26,146,21,21,4,4,2,999984,...,10,0.1420,0,8,24,24,-4.0000,21.5000,986,0
999984,2018,5,20,140,20,20,6,6,2,999985,...,1,0.0000,0,12,0,249,329.3100,95.8333,15580,1343
999985,2017,5,24,144,21,21,2,2,2,999986,...,6,0.0000,0,8,200,0,0.0000,0.0000,0,0
999986,2017,6,18,169,24,24,6,6,2,999987,...,18,0.0000,0,2,0,5,-50.0000,7.8333,0,2519
999987,2018,3,11,70,10,10,6,6,1,999988,...,12,0.0000,0,9,0,2,0.0000,1.0000,0,0
999988,2017,12,29,363,52,52,4,4,4,999989,...,7,0.0000,0,8,0,12,300.0000,5.3333,4619,0
999989,2018,2,14,45,7,7,2,2,1,999990,...,3,0.0000,0,15,160,11,-35.2900,19.0000,0,0
999990,2018,2,10,41,6,6,5,5,1,999991,...,1,0.0000,0,6,1,1,0.0000,2.5000,0,0
999991,2017,11,20,324,47,47,0,0,4,999992,...,0,0.0000,0,6,114,122,12.9600,76.1666,7551,444
999992,2018,5,5,125,18,18,5,5,2,999993,...,3,0.0000,0,4,126,47,291.6600,27.3333,0,21
999993,2017,5,17,137,20,20,2,2,2,999994,...,0,0.0000,0,7,4,3,50.0000,2.0000,0,0
999994,2018,1,8,8,2,2,0,0,1,999995,...,3,0.0000,0,7,161,31,-24.3900,40.0000,0,0
999995,2017,11,22,326,47,47,2,2,4,999996,...,2,0.0000,0,7,108,10,-9.0900,11.8333,267,0
999996,2017,11,7,311,45,45,1,1,4,999997,...,8,0.3330,0,9,208,9,-66.6600,32.8333,286,0
999997,2018,4,3,93,14,14,1,1,2,999998,...,1,0.0000,0,5,210,4,300.0000,5.1666,0,11
999998,2018,2,28,59,9,9,2,2,1,999999,...,3,0.0000,0,6,211,51,-89.6700,155.8333,230,0
999999,2017,12,25,359,52,52,0,0,4,1000000,...,15,1.0000,0,5,0,1,-75.0000,3.1666,0,0

In [28]:
## ------------------ ##
# vndr_id
## ------------------ ##

# convert vendor id to numeric using one hot encoding
from sklearn.feature_extraction import DictVectorizer

oneHotEnc = DictVectorizer()

# X_vndr_id = pd.DataFrame(oneHotEnc.fit_transform(X_copy['vndr_id']).toarray())

print(oneHotEnc.fit_transform(X_copy['vndr_id']).toarray())

AttributeError: 'str' object has no attribute 'items'